config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'signup' => 'users#new'
  resources :users
  get "about" => "pages#about"
  get "team" => "pages#team"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def team
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer id="MainFooter" role="contentinfo" class="footer--main">
    <div class="page-width page-width--fluid footer-top">
      <div class="grid-container">
        
<div class="footer-nav">
  <a href="/about">About</a>
  <a href="/careers">Careers</a>
  <a href="/blog">Blog</a>
  <a href="//blog">Press</a>
  <a href="/sitemap">Sitemap</a>
</div>

<!-- standard footer -->
<div class="grid-item grid-item--footer hide--mobile">
  <h3 class="footer-heading heading--5 hide--mobile">Ecommerce</h3>
  <a class="footer-link " href="/online">Sell online</a>
  <a class="footer-link " href="/online/ecommerce-solutions">Features</a>
  <a class="footer-link " href="/examples">Examples</a>
  <a class="footer-link " href="/website">Website builder</a>
  <a class="footer-link " href="/tour">Online retail</a>
  <a class="footer-link " href="/tour/ecommerce-website">Ecommerce website</a>
</div>

<div class="grid-item grid-item--footer hide--mobile footer-column--nameless">
  <a class="footer-link " href="/tour/website-design">Store design</a>
  <a class="footer-link " href="/tour/shopping-cart">Shopping cart</a>
  <a class="footer-link " href="/tour/ecommerce-hosting">Ecommerce hosting</a>
  <a class="footer-link " href="/mobile">Mobile commerce</a>
  <a class="footer-link " href="/">Ecommerce software</a>
  <a class="footer-link " href="/faq">FAQ</a>
</div>

<div class="grid-item grid-item--footer hide--mobile">
  <h3 class="footer-heading heading--5">Point of sale</h3>
  <a class="footer-link " href="/pos">Sell in person</a>
  <a class="footer-link " href="/pos/features">iPad POS</a>
  <a class="footer-link " href="/pos/hardware">Hardware</a>
  <a class="footer-link " href="/pos/software">POS software</a>
  <a class="footer-link " href="/pos/faq">FAQ</a>
</div>

<div class="grid-item grid-item--footer grid--mobile">
  <h3 class="footer-heading heading--5">Help</h3>
  <a class="footer-link " href="//docs.shopify.com/support">24/7 Support</a>
  <a class="footer-link " href="//docs.shopify.com">Shopify Docs</a>
  <a class="footer-link " href="https://ecommerce.shopify.com/forums">Ecommerce Forums</a>
  <a class="footer-link " href="//docs.shopify.com/api">API Docs</a>
  <a class="footer-link " href="/tools">Free tools</a>
</div>

<div class="grid-item grid-item--footer grid--last grid--mobile">
  <h3 class="footer-heading heading--5">Shopify</h3>
  <a class="footer-link " href="/contact">Contact</a>
  <a class="footer-link " href="/partners">Partner program</a>
  <a class="footer-link " href="/affiliates">Affiliate program</a>
  <a class="footer-link " href="//developers.shopify.com">App developers</a>
  <a class="footer-link " href="http://investors.shopify.com">Investors</a>

    <a class="footer-link " href="/blog/topics">Blog topics</a>

</div>

      </div>
    </div>

  <div class="page-width page-width--fluid">
  <div class="grid-container footer-bottom">
    <div class="footer-bottom-item footer-bottom__social">
      <a class="footer-social__icon " target="_blank" rel="me" data-ga-event="Social" data-ga-action="Twitter" data-ga-label="Footer" href="https://twitter.com/shopify"><svg aria-labelledby="social-twitter-6709729ddc395d97a344d92709637878-title" role="img" class="icon"><title id="social-twitter-6709729ddc395d97a344d92709637878-title">Twitter</title><use xlink:href="#social-twitter" /></svg></a>
      <a class="footer-social__icon " target="_blank" rel="me" data-ga-event="Social" data-ga-action="YouTube" data-ga-label="Footer" href="https://www.youtube.com/user/shopify"><svg aria-labelledby="social-youtube-d0222865757ed02ba7339707df6a4b3c-title" role="img" class="icon"><title id="social-youtube-d0222865757ed02ba7339707df6a4b3c-title">YouTube</title><use xlink:href="#social-youtube" /></svg></a>
      <a class="footer-social__icon " target="_blank" rel="me" data-ga-event="Social" data-ga-action="Instagram" data-ga-label="Footer" href="https://www.instagram.com/shopify"><svg aria-labelledby="social-instagram-cb9304932d5777ef4abf698a3862c97d-title" role="img" class="icon"><title id="social-instagram-cb9304932d5777ef4abf698a3862c97d-title">Instagram</title><use xlink:href="#social-instagram" /></svg></a>
      <a class="footer-social__icon " target="_blank" rel="me" data-ga-event="Social" data-ga-action="LinkedIn" data-ga-label="Footer" href="https://www.linkedin.com/company/shopify"><svg aria-labelledby="social-linkedin-996999932cdb20c1669b1681d114b725-title" role="img" class="icon"><title id="social-linkedin-996999932cdb20c1669b1681d114b725-title">LinkedIn</title><use xlink:href="#social-linkedin" /></svg></a>
      <a class="footer-social__icon " target="_blank" rel="me" data-ga-event="Social" data-ga-action="Pinterest" data-ga-label="Footer" href="https://www.pinterest.com/shopify"><svg aria-labelledby="social-pinterest-aab98241d0f4776f8c558a086ae7bf4f-title" role="img" class="icon"><title id="social-pinterest-aab98241d0f4776f8c558a086ae7bf4f-title">Pinterest</title><use xlink:href="#social-pinterest" /></svg></a>
      <a class="footer-social__icon " target="_blank" rel="me" data-ga-event="Social" data-ga-action="Plus" data-ga-label="Footer" href="https://plus.google.com/+shopify"><svg aria-labelledby="social-plus-8ff79195302defb14646709121722bd4-title" role="img" class="icon"><title id="social-plus-8ff79195302defb14646709121722bd4-title">Google Plus</title><use xlink:href="#social-plus" /></svg></a>
    </div>

    <div class="footer-bottom-item footer-bottom__links">
      
    <a href="/legal/terms">Terms of Service</a>
    <a href="/legal/privacy">Privacy Policy</a>

  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "@ the mat", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div> <!-- /.container collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>@ the mat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
	<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%=content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
		<%=render 'layouts/footer' %>	
	</div>

	</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Coming soon...</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to @ the mat</h1>
	<p> 
		<%= link_to "Log In", "#", class: "btn btn-default btn-lg" %>
		<%= link_to "Sign Up", "#", class: "btn btn-primary btn-lg" %>
	</p>
</div>

app/views/pages/team.html.erb
<h1>The Team</h1>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>


  
    </div>
  </div>
</div>